/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pIUoDPT0B4W
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import axios from 'axios'
import { Loader2, Play } from 'lucide-react'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import { useWatch } from '../WatchProvider'

export function VideoList() {
  const { watchId, UpdateWatchId } = useWatch()
  const [isLoading, setIsLoading] = useState(false)
  const [videos, setVideos] = useState<any[]>([])

  useEffect(() => {
    const loadVideos = async () => {
      try {
        setIsLoading(true)
        await axios
          .get(`/api/video?q=${watchId}`)
          .then((res) => {
            const data = res.data['result']
            console.log('res.data:', data)
            setVideos(data['lists'])
          })
          .catch((res) => {
            console.log('/api/video error:', res)
          })
        // console.log('result.data:', result.data)
        // setVideos(result.data.lists)
        console.log('videos:', videos)
        videos.map((video, index) => {
          console.log(video, index)
        })
        console.log(typeof videos)
        setIsLoading(false)
      } catch (error) {
        console.log(error)
      }
    }

    loadVideos()
  }, [watchId])

  const createTask = async () => {
    try {
      const result = await axios.get(`/api/task?q=${watchId}`)
      console.log('result.data:', result.data)
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <>
      <section className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4 md:p-6'>
        {isLoading ? (
          <Loader2 className='mr-4 h-16 w-16 animate-spin' />
        ) : (
          videos.map((video, index) => (
            <>
              <div className='relative group overflow-hidden rounded-lg'>
                <Link
                  className='absolute inset-0 z-10'
                  href={`/dashboard/watch?url=${video.href}`}>
                  <span className='sr-only'>Play</span>
                  <div className='absolute inset-0 flex items-center justify-center'>
                    <Play className='w-12 h-12 drop-shadow-lg' />
                  </div>
                </Link>
                <div>
                  <img
                    className='w-[480px] h-auto'
                    src={video.thumbnail}
                    alt='Youtube video cover'
                  />
                </div>

                {/* <Image
                  alt='Video Thumbnail'
                  className='w-[480px] h-auto'
                  height={360}
                  src='https://i.ytimg.com/vi/YDIQo-py2bI/hqdefault.jpg'
                  // style={{
                  //   aspectRatio: '480/360',
                  //   objectFit: 'cover',
                  // }}
                  width={480}
                  srcSet='https://i.ytimg.com/vi/YDIQo-py2bI/hqdefault.jpg 480w'
                /> */}
                <div className='bg-white p-4 dark:bg-gray-950'>
                  <h3 className='font-semibold text-lg md:text-xl line-clamp-2'>
                    {video.title}
                  </h3>
                  <div className='flex items-center justify-between text-sm text-gray-500 dark:text-gray-400'>
                    <span>{video.author}</span>
                    <span>{video.period}</span>
                  </div>
                  <div className='flex items-center justify-between text-sm text-gray-500 dark:text-gray-400'>
                    <span>{video.published}</span>
                    <span>{video.viewCount}</span>
                  </div>
                </div>
              </div>
            </>
          ))
        )}
      </section>
    </>
  )
}
