/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pIUoDPT0B4W
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import axios from 'axios'
import { Play } from 'lucide-react'
import Link from 'next/link'
import { useEffect, useState } from 'react'

export function VideoList() {
  const [isLoad, setIsLoad] = useState(false)
  const [videos, setVideos] = useState<any[]>([])

  useEffect(() => {
    const loadVideos = async () => {
      try {
        const result = await axios.get(`/api/video`)
        console.log('result.data:', result.data)
        setVideos(result.data.lists)
        console.log('videos:', videos)
        videos.map((video, index) => {
          console.log(video, index)
        })
        console.log(typeof videos)
      } catch (error) {
        console.log(error)
      }
    }

    loadVideos()
  }, [])

  return (
    <>
      {/* <button
        onClick={handleLoadVideos}
        className='border rounded-md p-1 font-semibold'>
        Load
      </button> */}
      <section className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4 md:p-6'>
        {videos.map((video, index) => (
          <>
            <div className='relative group overflow-hidden rounded-lg'>
              <Link
                className='absolute inset-0 z-10'
                href={`/dashboard/watch?url=${video.href}`}>
                <span className='sr-only'>Play</span>
                <div className='absolute inset-0 flex items-center justify-center'>
                  <Play className='w-12 h-12 text-white drop-shadow-lg' />
                  {/* <PlayIcon className='w-12 h-12 text-white drop-shadow-lg' /> */}
                </div>
              </Link>
              <img
                alt='Video Thumbnail'
                className='object-cover w-full h-56'
                height={225}
                src='/placeholder.svg'
                style={{
                  aspectRatio: '400/225',
                  objectFit: 'cover',
                }}
                width={400}
              />
              <div className='bg-white p-4 dark:bg-gray-950'>
                <h3 className='font-semibold text-lg md:text-xl line-clamp-2'>
                  {video.title}
                </h3>
                <div className='flex items-center justify-between text-sm text-gray-500 dark:text-gray-400'>
                  <span>{video.author}</span>
                  <span>5:32</span>
                </div>
              </div>
            </div>
          </>
        ))}
      </section>
    </>
  )
}
