/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pIUoDPT0B4W
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import axios from 'axios'
import { Loader2, Play } from 'lucide-react'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import { useWatch } from '../WatchProvider'

export function VideoList() {
  const { watchId, UpdateWatchId } = useWatch()
  const [isLoading, setIsLoading] = useState(false)
  const [videos, setVideos] = useState<any[]>([])

  useEffect(() => {
    const loadVideos = async () => {
      try {
        setIsLoading(true)
        const result = await axios.get(`/api/video?q=${watchId}`)
        console.log('result.data:', result.data)
        setVideos(result.data.lists)
        console.log('videos:', videos)
        videos.map((video, index) => {
          console.log(video, index)
        })
        console.log(typeof videos)
        setIsLoading(false)
      } catch (error) {
        console.log(error)
      }
    }

    loadVideos()
  }, [watchId])

  return (
    <>
      <section className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4 md:p-6'>
        {isLoading ? (
          <Loader2 className='mr-4 h-16 w-16 animate-spin' />
        ) : (
          videos.map((video, index) => (
            <>
              <div className='relative group overflow-hidden rounded-lg'>
                <Link
                  className='absolute inset-0 z-10'
                  href={`/dashboard/watch?url=${video.href}`}>
                  <span className='sr-only'>Play</span>
                  <div className='absolute inset-0 flex items-center justify-center'>
                    <Play className='w-12 h-12 drop-shadow-lg' />
                  </div>
                </Link>
                <Image
                  alt='Video Thumbnail'
                  className='object-cover w-full h-56'
                  height={225}
                  src='/placeholder.svg'
                  style={{
                    aspectRatio: '400/225',
                    objectFit: 'cover',
                  }}
                  width={400}
                />
                <div className='bg-white p-4 dark:bg-gray-950'>
                  <h3 className='font-semibold text-lg md:text-xl line-clamp-2'>
                    {video.title}
                  </h3>
                  <div className='flex items-center justify-between text-sm text-gray-500 dark:text-gray-400'>
                    <span>{video.author}</span>
                    <span>5:32</span>
                  </div>
                </div>
              </div>
            </>
          ))
        )}
      </section>
    </>
  )
}
