/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pIUoDPT0B4W
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Loader2, Play } from 'lucide-react'
import Link from 'next/link'
import { useWatch } from './WatchProvider'
import { useMutation } from '@tanstack/react-query'
import { getVideos } from '@/app/actions'
import { useEffect } from 'react'

export function VideoList() {
  const { watchId } = useWatch()
  console.log('VideoList:', watchId)
  console.log('watchId length:', watchId.length)

  const {
    data,
    mutate: searchVideos,
    isPending,
    isError,
  } = useMutation({
    mutationFn: async () => await getVideos({ author: watchId }),
    mutationKey: ['author'],
  })

  if (isError) return <div>Sorry There was an Error</div>
  if (!isPending) {
    console.log('data:', data)
  }

  return (
    <>
      <section className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4 md:p-6'>
        <button
          onClick={() => {
            searchVideos()
          }}>
          Click me
        </button>
        {isPending && <Loader2 className='mr-4 h-16 w-16 animate-spin' />}
        {!isPending &&
          data?.map((video) => (
            <>
              <div className='relative group overflow-hidden rounded-lg'>
                <Link
                  className='absolute inset-0 z-10'
                  href={`/dashboard/watch?url=${video.href}`}>
                  <span className='sr-only'>Play</span>
                  <div className='absolute inset-0 flex items-center justify-center'>
                    <Play className='w-12 h-12 drop-shadow-lg' />
                  </div>
                </Link>
                <div>
                  <img
                    className='w-[480px] h-auto'
                    src={video.thumbnail}
                    alt='Youtube video cover'
                  />
                </div>

                <div className='bg-white p-4 dark:bg-gray-950'>
                  <h3 className='font-semibold text-lg md:text-xl line-clamp-2'>
                    {video.title}
                  </h3>
                  <div className='flex items-center justify-between text-sm text-gray-500 dark:text-gray-400'>
                    <span>{video.author}</span>
                    <span>{video.period}</span>
                  </div>
                  <div className='flex items-center justify-between text-sm text-gray-500 dark:text-gray-400'>
                    <span>{video.published}</span>
                    <span>{video.viewCount}</span>
                  </div>
                </div>
              </div>
            </>
          ))}
      </section>
    </>
  )
}
